name: Launcher version bump
on:

  push:
    branches: [ "main"]


  workflow_dispatch:
jobs:
  windows-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: setup git
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        #parsed string
        parsed = cat WpfApp5/AssemblyInfo.cs | tail -n 2 | head -n 1 | sed -E 's/.*AssemblyVersion\("([0-9]+\.[0-9]+\.[0-9]+)"\).*/\1/' | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}'
        echo $parsed
        sed -i "s/\[assembly: AssemblyVersion(\"[0-9]\+\.[0-9]\+\.[0-9]\+\")\]/[assembly: AssemblyVersion(\"$parsed\")]/" WpfApp5/AssemblyInfo.cs
        cat WpfApp5/AssemblyInfo.cs
        
